version: '3.7'
services :
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: graphql-test
    restart: always
    ports:
      - 5433:5432
    env_file:
      - database.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db